#define PB03 GPIO(GPIO_PORTB, 3)
#define PB05 GPIO(GPIO_PORTB, 5)
#define PB14 GPIO(GPIO_PORTB, 14)
#define PB15 GPIO(GPIO_PORTB, 15)
#define PB16 GPIO(GPIO_PORTB, 16)
#define PB17 GPIO(GPIO_PORTB, 17)
#define PB18 GPIO(GPIO_PORTB, 18)
#define PB19 GPIO(GPIO_PORTB, 19)
#define PB20 GPIO(GPIO_PORTB, 20)
#define PB21 GPIO(GPIO_PORTB, 21)

#define PA02 GPIO(GPIO_PORTA, 2)
#define PA14 GPIO(GPIO_PORTA, 14)
#define PA16 GPIO(GPIO_PORTA, 16)
#define PA20 GPIO(GPIO_PORTA, 20)
#define PA21 GPIO(GPIO_PORTA, 21)
#define PA22 GPIO(GPIO_PORTA, 22)

#define PC00 GPIO(GPIO_PORTC, 0)
#define PC01 GPIO(GPIO_PORTC, 1)
#define PC02 GPIO(GPIO_PORTC, 2)
#define PC24 GPIO(GPIO_PORTC, 24)

#define FPGA_SOFT_RESET	PB16
#define FPGA_RX_ENABLE  PB18
#define FPGA_TX_GO      PB19
#define FPGA_FLAG_FILL  PA22

#define FPGA_IDLE	PA20
#define FPGA_NO_CLOCK	PA21

#define LED_SD		PA02
#define LED_ECONET	PA01
#define LED_ONLINE	PA00
#define LED_ERROR	PC00
#define LED_ETHERNET	PC01
#define LED_NO_CLOCK	PC02

